# Generated by Django 3.1.5 on 2021-01-09 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thumbnailer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
